name: Nuget Package Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1  
      
      - name: Setup .NET environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      
      - name: Add source to NuGet configuration
        run: dotnet nuget add source https://nuget.pkg.github.com/ZyshchykMaksim/index.json --name "github" --username ZyshchykMaksim --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      
      - name: Build project
        run: dotnet build --configuration Release
      
      - name: Pack package
        run: dotnet pack -c Release -o

      - name: Push nuget package to GitHub Registry
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate

    
